import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Toaster } from "@/components/ui/sonner";
import { DialogProvider } from "./providers/dialog-provider";
import { AuthProvider } from "./providers/auth-provider";
import { ScrollToTop } from "@/components/scroll-to-top";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
		>
			<body className={inter.className}>
				<AuthProvider>
					<DialogProvider>
						{children}
						<Toaster richColors />
						<ScrollToTop/>
					</DialogProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
